### ISSUE TITLE
Apphud.submitReceipt missing

### ISSUE THREAD

**Issue by nosovk** [apphud/ApphudSDK-Flutter#41]
We implemented Apphud in observer mode in our app, but no purchases tracked in IOS either Android.
According to [docs](https://github.com/apphud/docs/blob/master/docs/sdk-integration.md#making-a-purchase) there should be `Apphud.submitReceipt` method, but it's missing in https://github.com/apphud/ApphudSDK-Flutter/blob/main/lib/apphud.dart

**Comment by bgoncharuck** [comment]
I have the same issue

**Comment by ren6** [comment]
@nosovk Hello! According to docs, you should call `Apphud.syncPurchases()` [on Android](https://docs.apphud.com/getting-started/sdk-integration/flutter#purchase-in-observer-mode-android) and do nothing on iOS, since iOS purchases are tracked automatically. Please check shared secret on iOS and bundle id if you have purchase tracking issues. Best regards

**Comment by nosovk** [comment]
We make `Apphud.syncPurchases()`, but no success. I've opened support ticket
